name: Generate Snake Animation

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ allows pushing to the output branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3   # ✅ required before running Platane/snk

      - name: Generate GitHub contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: gowshekan   # ✅ your GitHub username
          outputs: dist/snake.svg

      - name: Push generated snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
